<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>flink-algorithm</artifactId>
        <groupId>com.algorithm</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>flink-algorithm-job</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>algorithm-detection-rms-influxdb</module>
        <module>algorithm-forecast-rms-influxdb</module>
        <module>algorithm-early-degeneration-rms-influxdb</module>
        <module>algorithm-of-flink-save</module>
        <module>topic-distribute</module>
        <module>algorithm-deduplication-adjacent</module>
        <module>algorithm-deduplication-hash</module>
        <module>dc-guard</module>
        <module>dc-cms-influxdb</module>
        <module>task-config</module>
        <module>task-config-algorithm</module>
        <module>algorithm-detection-kafka-influxdb</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.algorithm</groupId>
            <artifactId>flink-algorithm-common</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>