#job
job.name=algorithm-deduplication-adjacent
#kafka
#kafka.brokers=kafka1.bg.local:9094,kafka2.bg.local:9095,kafka3.bg.local:9096
kafka.brokers=192.168.16.222:9092
kafka.group.id=algorithm_deduplication_adjacent_group
kafka.topics=algorithm_deduplication_adjacent

#kafka_sink
#kafka.sink.brokers=kafka1.bg.local:9094,kafka2.bg.local:9095,kafka3.bg.local:9096
kafka.sink.brokers=192.168.16.222:9092
kafka.sink.topics=algorithm_sink_deduplication_adjacent