server:
  port: 7200

spring:
  application:
    name: model3dlk
  cloud:
    inetutils:
      ignored-interfaces:
        - VMware.*
        - VirtualBox.*
        - vEthernet.*
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:application-@profiles.active@.yml
      - nacos:${spring.application.name}-@profiles.active@.yml
  datasource:  # 示例数据源配置，注意修改也可配置至 nacos
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: zcx123456
    password: root
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:new_algorithom_Repository}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://192.168.65.44:3306/new_algorithom_Repository?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

  servlet:
    multipart: #限制minio文件上传大小
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB

# spring security 配置
security:
  oauth2:
    client:
      client-id: pig
      client-secret: pig
      scope: server

minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  accesskey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  modelBucket: modelfile  #模型桶名
  imageBucket: modelimg   #图片桶名

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
