#job
job.name=topic-distribute
#kafka
#kafka.brokers=kafka1.bg.local:9094,kafka2.bg.local:9095,kafka3.bg.local:9096
kafka.brokers=177.8.0.10:9092,177.8.0.11:9093,177.8.0.12:9094
kafka.group.id=topic_distribute_group
kafka.topics=sensor_part_.*

#kafka_sink
#kafka.sink.brokers=kafka1.bg.local:9094,kafka2.bg.local:9095,kafka3.bg.local:9096
kafka.sink.brokers=177.8.0.10:9092,177.8.0.11:9093,177.8.0.12:9094

#influxDB
#influxDB.url=http://influxdb.bg.local/
#influxDB.url=http://influxdb/
#influxDB.url=http://177.8.0.13:8086/
influxDB.url=http://177.8.0.14:8086/

#192.168.20.104
#influxDB.token=I6j8FKO-1xLCeYTtbjruXGmGu6bCYepnl0zfFDwE5pf8iO7pOpO2daajx3C3EKIu0fvHIyGcSQJd70rajF5qHg==


influxDB.token=b-6wkycz9XMJJG_Ad49aYUk_KicySSGVSbSaa8RYp6EyObz961qKw0zH4Bp8D6MMT34vzm2a6JJ-PKg7uBOQUA==
influxDB.bucket=bigdata
influxDB.organization=bigdata