server.port=8857
spring.application.name=dc-cms-influxdb
#kafka
spring.kafka.bootstrap-servers=192.168.16.219:9092
#spring.kafka.bootstrap-servers=177.8.0.10:9092,177.8.0.11:9093,177.8.0.12:9094
spring.kafka.consumer.group-id=dc_CMS-group
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-offset-reset=earliest 

#influxDB
influxdb.url=http://192.168.16.219:8086/
#influxdb.url=http://177.8.0.14:8086/
influxdb.token=b-6wkycz9XMJJG_Ad49aYUk_KicySSGVSbSaa8RYp6EyObz961qKw0zH4Bp8D6MMT34vzm2a6JJ-PKg7uBOQUA==
influxdb.bucket=dc_CMS
influxdb.org=bigdata