# ???? WEB ????
server.port=8859
spring.application.name=flink-algorithm-sendData-0.0.1


# Kafka??
kafka.servers=192.168.16.219:9092
#kafka.servers=192.168.16.219:9092
kafka.cms.topic=al_source
kafka.gru.topic=dc_source_170
kafka.gruae.topic=dc_source_190
kafka.lstm.topic=dc_source_218
kafka.lstmae.topic=dc_source_218
kafka.resnet.topic=dc_CMS

# MQTT ?????
mqtt.server=tcp://192.168.65.84:1883
mqtt.lstmae.topic=dc_algorithm_LSTMAE


# ????

file.gru.name=LSTM_GRU_GRUAE.csv
file.gruae.name=LSTM_GRU_GRUAE.csv
file.lstm.name=LSTM_GRU_GRUAE.csv
file.lstmae.name=LSTMAE_pghk_11.csv
file.resnet.name=test_for_diagnose.txt

