#job
job.name=algorithm-early-degeneration-rms-insert-influxdb
#kafka
#kafka.brokers=kafka1.bg.local:9094,kafka2.bg.local:9095,kafka3.bg.local:9096
kafka.brokers=kafka-headless:9092
kafka.group.id=algorithm_sink_early_degeneration_rms_influxdb_group
kafka.topics=algorithm_sink_early_degeneration_rms
#influxDB
#influxDB.url=http://influxdb.bg.local/
influxDB.url=http://influxdb/
influxDB.token=I6j8FKO-1xLCeYTtbjruXGmGu6bCYepnl0zfFDwE5pf8iO7pOpO2daajx3C3EKIu0fvHIyGcSQJd70rajF5qHg==
influxDB.bucket=bigdata
influxDB.organization=bigdata