CREATE TABLE IF NOT EXISTS `al_diagnosis_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `diagnosis_key` CHAR(64) NOT NULL COMMENT '报警事件与诊断算法组成的幂等键',
  `alarm_task_id` VARCHAR(64) NOT NULL COMMENT '状态监测任务ID',
  `alarm_time` VARCHAR(40) NOT NULL COMMENT '标准化ISO-8601告警时间',
  `requested_time` VARCHAR(40) DEFAULT NULL COMMENT '诊断请求时间',
  `matched_time` VARCHAR(40) DEFAULT NULL COMMENT '实际匹配的CMS数据时间',
  `time_offset_seconds` DECIMAL(12,3) DEFAULT NULL COMMENT '匹配数据与告警时间差（秒）',
  `farm_name` VARCHAR(128) NOT NULL COMMENT '场景/小区名称',
  `turbine_name` VARCHAR(128) NOT NULL COMMENT '设备实例名称',
  `turbine_code` VARCHAR(255) NOT NULL COMMENT '设备实例编码',
  `node_id` VARCHAR(64) NOT NULL COMMENT '测点节点ID',
  `node_code` VARCHAR(64) DEFAULT NULL COMMENT '测点节点编码',
  `node_name` VARCHAR(128) NOT NULL COMMENT '测点名称',
  `monitor_point_id` VARCHAR(128) DEFAULT NULL COMMENT 'CMS测点标识',
  `algorithm_id` BIGINT NOT NULL COMMENT '故障诊断算法ID',
  `algorithm_short_name` VARCHAR(64) NOT NULL COMMENT '故障诊断算法简称',
  `algorithm_task_id` BIGINT DEFAULT NULL COMMENT '算法执行任务ID',
  `diagnosis_status` TINYINT NOT NULL DEFAULT 1 COMMENT '1处理中 2成功 3失败',
  `is_fault` TINYINT DEFAULT NULL COMMENT '0正常 1故障',
  `fault_code` INT DEFAULT NULL COMMENT '模型故障类别编码',
  `fault_name` VARCHAR(128) DEFAULT NULL COMMENT '模型故障类别名称',
  `dictionary_fault_code` VARCHAR(32) DEFAULT NULL COMMENT '故障字典类别编码',
  `dictionary_fault_name` VARCHAR(128) DEFAULT NULL COMMENT '故障字典类别名称',
  `confidence` DECIMAL(12,10) DEFAULT NULL COMMENT '模型最高类别概率',
  `result_json` JSON DEFAULT NULL COMMENT '完整模型输出',
  `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_diagnosis_key` (`diagnosis_key`),
  KEY `idx_device_fault` (`turbine_code`, `diagnosis_status`, `is_fault`, `dictionary_fault_name`),
  KEY `idx_alarm_time` (`alarm_time`),
  KEY `idx_algorithm_task` (`algorithm_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='故障诊断结果记录';
